### ISSUE TITLE
Possible Memory Leak?

### ISSUE THREAD

**Issue by scshadrick** [GRIFFINCollaboration/NTuple2EventTree#16] opened 2019-02-26 18:32 UTC
When grsiproofing a 10 million event analysis.root file generated from detectorsims and thru NTuple2EventTree, it ramps up in RAM usage up to 60Gb linearly throughout the run.  Using a 35 million event analysis.root file from real data, it maxes out the RAM to about 3Gb.  Is there a possible memory issue stemming from the NTuple2EventTree converter or is this normal?

**Comment by r3dunlop** [comment] 2019-02-26 18:33
How many workers are you running and how many/what type of spectra are you trying to create. PROOF creates a copy of each hist for each worker. The RAM should have very little to do with the number of entries unless you are using a sparse matrix.

**Comment by scshadrick** [comment] 2019-02-26 18:37
I use 4 workers with 42 TH1/2F/D type histograms.  Should I limit the amount of histograms?

**Comment by r3dunlop** [comment] 2019-02-26 18:39
Ah, after re-reading it seems you are running the same Proof script? If so, the number of workers shouldn’t be an issue if it works for experimental data.

There shouldn’t be that much memory being allocated over the course of a sort. My guesses right now are either a sparse matrix getting much more data than in experiment (which it seems like isn’t the case), or something being off with time stamping (or addresses) causing events to be held in memory/millions of channels being created in memory?

**Comment by scshadrick** [comment] 2019-02-26 18:41
Could it be an issue from having BranchAddresses set to LaBr, Bgo, and PACES without using them?

**Comment by r3dunlop** [comment] 2019-02-26 18:45
You can try removing that. It *shouldn’t* be an issue though as the pointer just moves along to point previously allocated memory. I believe the way Root works is it allocates one TGriffin, for example, per worker. The branch pointer points at that memory. When you get the next entry, it creates a new TGriffin, and starts dealing with deleting the old one. The branch pointer points at the new memory now. I’d have a hard time believe that would behave differently for our fake tree compared to a real tree as they use the same libraries to create them.

**Comment by r3dunlop** [comment] 2019-02-26 18:49
Can you try printing out some entries from the tree to see if there are any strange addresses, address->channel mappings, timestamps, etc?

**Comment by scshadrick** [comment] 2019-02-26 19:04
I checked the timestamp for fDescantHits.TGRSIDetectorHit.fTimeStamp and it reads a mean of -2.354e+15 with giant bins encompassing 0 even.  That doesn't seem right.
![timestampdescant](https://user-images.githubusercontent.com/20971746/53439110-8e91cc80-39be-11e9-9bd1-09ad1a866e91.png)

**Comment by r3dunlop** [comment] 2019-02-26 19:06
Depends on how it’s constructing events. It might not care about timestamps if it’s treating simulated coincidences sort of like a “trigger” condition. Do you have separate entries in this tree, or is it one gigantic entry. Maybe it has to be sorted like it was triggered data? I’m not too familiar with performing these analyses, just the structure of the experimental sort code itself.

**Comment by scshadrick** [comment] 2019-02-26 19:13
Every event triggered landed in the one bin for each Hit Branch, if that's what you're asking.  I'm not sure how this is affecting things either, but it does seem a bit off.

**Comment by VinzenzBildstein** [comment] 2019-02-26 19:21
As far as I can see from the code we use the time from the beginning of the event to set the timestamp (it's in seconds and we multiply it by 1e8). So you should get positive timestamps only. The plot your showing might be weird because of root messing up the binning. Try and plot it by hand into a histogram of appropriate size and binning:
```
AnalysisTree->Draw("fDescantHits.fTimeStamp>>h(10000,-5e9,5e9)")
```
You can always adjust the limits of the histogram to figure out how large it has to be.

**Comment by scshadrick** [comment] 2019-02-26 19:40
![image](https://user-images.githubusercontent.com/20971746/53441239-999b2b80-39c3-11e9-8ce3-d77a99b6c0d3.png)

It shouldn't matter that the default binning is off, right?

**Comment by VinzenzBildstein** [comment] 2019-02-26 19:50
No, that looks quite resonable. And since we already build events in the NTuple2Event tree, there isn't any issue with mixing timestamps either. Not sure what could cause the increased memory usage. The program writes normal detector data to the analysis file, so the sorting should be the same as for real data.
I'll have to try and see if I can reproduce that.

**Comment by r3dunlop** [comment] 2019-02-26 19:51
Could it have something to do with addresses/TChannels/cal files?

**Comment by VinzenzBildstein** [comment] 2019-02-27 17:09
I've tested this with a simple GRIFFIN simulation and I don't see this. I only simulated 1M events and then copied the output files to increase the statistics to 10M, but that shouldn't change things.
Using grsiproof with the ExampleEventSelector, the memory usage grew up to 4.4 G (RES not VIRT) which corresponds to 3.5% for our server.
I also ran a file with real data which had 5600507 entries (compared to 5566329 in the simulation). This time grsiproofs clients never went above 350 M, so 0.2% of our servers memory. Since this is reproducible I can try and look into this.

**Comment by VinzenzBildstein** [comment] 2019-02-27 21:00
I just noticed that the version I had used to sort the data had some weird output in it which spammed the grsisort.log file (almost 500MB). After recompiling grsisort without that output the grsisort.log is only 14 kB and the maximum memory usage went way down to 500 MB.
So my guess would be that you're also getting a lot of output printed to grsisort.log? Can you check what that file looks like after running grsiproof on simulated data @scshadrick?

**Comment by scshadrick** [comment] 2019-02-27 21:11
The grsisort.log file in my NTuple2EventTree is only 1325 bytes, I'm not seeing any .log files that come close to 500Mb in size.

**Comment by VinzenzBildstein** [comment] 2019-02-28 14:42
There will be only one log file, the grsisort.log. This also gets overwritten every time you run grsiproof. So if you ran grsiproof on real data after running it on the simulation, you would only see the small output from the real data.
Can you post your grsisort.log file here please?

**Comment by scshadrick** [comment] 2019-02-28 17:15
Is it in the anaylsis file's directory or in the NTuple2EventTree directory?  I'm attaching the one from the directory I was running grsiproof in. 
[grsisort.log.zip](https://github.com/GRIFFINCollaboration/NTuple2EventTree/files/2916073/grsisort.log.zip)

**Comment by VinzenzBildstein** [comment] 2019-02-28 17:40
That would be the correct one. The file gets created in whatever directory you run grsiproof in. Just to make sure, /media/steven/WorkData/DATAFEB19/10590pregrsi.root is a file with simulation data, yes? In that case I can't see why your version of grsiproof (seems to be a bit older) is different from mine (I used v.3.1.3.5 I believe) in memory usage.

Without being able to reproduce this bug it's going to be difficult to find the reason for it. I'll try again with a new clean v3 of the code to see if I can reproduce it.

**Comment by scshadrick** [comment] 2019-02-28 18:06
Yes, that would be the one. I've looked thru the source code a bit, and nothing stands out and the leak only occurs in grsiproof sessions.  It seems like grsiproof is having trouble deleting the objects after extracting the data it needs from them and holds onto them until the session is over.  I'm not sure why it would only do it with the simulated data and not real data as well tho.

**Comment by r3dunlop** [comment] 2019-02-28 18:57
Which objects is it holding on to? Can you try running with a single worker to see what happens? You can also see which objects it’s holding onto by using a single worker and adding a static integer that gets incremented in the ctor and lowered in the dtor. You can then put a print out or histogram or something that plays back that static int as time progresses.

Any chance you can throw a copy of the proof script up here as well?

**Comment by scshadrick** [comment] 2019-02-28 19:56
In which ctor/dtor should I be incrementing across? 

[Selector.zip](https://github.com/GRIFFINCollaboration/NTuple2EventTree/files/2916682/Selector.zip)

**Comment by r3dunlop** [comment] 2019-02-28 19:57
Whichever class you think is the issue. You can do it in TGriffin, TGriffinHit, etc.

**Comment by r3dunlop** [comment] 2019-02-28 20:20
This might not explain the difference between the two codes...But I do notice a leak in the script.

Each of the below functions leak as they create new TRandom3's and lose the pointer to scope before deleting:

- `TimeDiff(TDescantHit *d, TSceptarHit *s)` 
- `ToyNeutronEnergy(TDescantHit *d)`
- `InitialEnergyN(TDescantHit *d, TSceptarHit *s)`
- `IsValidHit(TDescantHit *d1, TDescantHit *d2, TSceptarHit *s)` 
- `TreeSelector::FillHistograms()`  <- this is a minor issue compared to the above

Is it possible that some of these functions are called far more often in simulation than in data? A quick check would be to correct the memory leak by deleting the pointers at the end of every function, or removing them from being allocated/used.

**Comment by scshadrick** [comment] 2019-02-28 20:26
That helps a little bit, but it still gets around 30G of RAM by the end of a 10million Li-11 event run.  Vinzenz also mentioned that even the exampleselector is using about 10x more RAM on simulated data as well vs. real data tho.

**Comment by r3dunlop** [comment] 2019-02-28 20:37
Maybe Vinzenz can correct me, but I think that was because of output buffers for the log file getting full rather than an issue with the code itself.

Ok. I got other stuff on the go (thesis) so I can't spend too much time digging into the data myself, so I'll just annoyingly throw out questions as I think of them. Maybe Vinzenz has some thoughts on these things:

- Are the entry sizes roughly the same in both formats? ie are there roughly n TGriffinHits per TGriffin in both formats, and do those add up to roughly the same number of bytes?
- Is there a TPPG in the simulated tree, and is something crazy happening with that?
- On that note, the things I could see causing problems are singleton classes like TGRSIRunInfo, TAnalysisOption,  TPPG, and the TChannelMap if they aren't intialized by the NTuple code properly, and the grsisort libraries aren't dealing with that hiccup properly.

**Comment by VinzenzBildstein** [comment] 2019-02-28 21:57
Definitely, in my case the difference in memory usage was fixed by removing the spurious output that filled the log file. I noticed that mainly because I ran grsiproof with valgrind to check where the memory leak was and noticed that a lot of memory was used for strings.
Maybe you can run the simulated and real data with valgrind (```valgrind --tool=massif grsiproof ...```) and either post the output here (if it's not too big), or process the output with ms_print and post the results of that?

**Comment by scshadrick** [comment] 2019-03-01 17:32
I'm going to post some warnings I get at the beginning of an NTuple2EventTree process.  It still works correctly, but this may help in tracking the issue:

Warning in <TEnvRec::ChangeValue>: duplicate entry <//=LaBr3> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <//=Sceptar> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <//=EightPi> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <//=Descant> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <//=Paces> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <offset== env.GetValue(Form("Griffin.BGO.Front.Left.%d.%d.Resolution.Offset",detector,crystal),1.100);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <linear== env.GetValue(Form("Griffin.BGO.Front.Left.%d.%d.Resolution.Linear",detector,crystal),0.00183744);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <quadratic== env.GetValue(Form("Griffin.BGO.Front.Left.%d.%d.Resolution.Quadratic",detector,crystal),0.0000007);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <cubic== env.GetValue(Form("Griffin.BGO.Front.Left.%d.%d.Resolution.Cubic",detector,crystal),0.);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <offset== env.GetValue(Form("Griffin.BGO.Front.Right.%d.%d.Resolution.Offset",detector,crystal),1.100);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <linear== env.GetValue(Form("Griffin.BGO.Front.Right.%d.%d.Resolution.Linear",detector,crystal),0.00183744);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <quadratic== env.GetValue(Form("Griffin.BGO.Front.Right.%d.%d.Resolution.Quadratic",detector,crystal),0.0000007);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <cubic== env.GetValue(Form("Griffin.BGO.Front.Right.%d.%d.Resolution.Cubic",detector,crystal),0.);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <offset== env.GetValue(Form("Griffin.BGO.Side.Left.%d.%d.Resolution.Offset",detector,crystal),1.100);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <linear== env.GetValue(Form("Griffin.BGO.Side.Left.%d.%d.Resolution.Linear",detector,crystal),0.00183744);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <quadratic== env.GetValue(Form("Griffin.BGO.Side.Left.%d.%d.Resolution.Quadratic",detector,crystal),0.0000007);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <cubic== env.GetValue(Form("Griffin.BGO.Side.Left.%d.%d.Resolution.Cubic",detector,crystal),0.);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <offset== env.GetValue(Form("Griffin.BGO.Side.Right.%d.%d.Resolution.Offset",detector,crystal),1.100);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <linear== env.GetValue(Form("Griffin.BGO.Side.Right.%d.%d.Resolution.Linear",detector,crystal),0.00183744);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <quadratic== env.GetValue(Form("Griffin.BGO.Side.Right.%d.%d.Resolution.Quadratic",detector,crystal),0.0000007);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <cubic== env.GetValue(Form("Griffin.BGO.Side.Right.%d.%d.Resolution.Cubic",detector,crystal),0.);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <offset== env.GetValue(Form("Griffin.BGO.Back.%d.%d.Resolution.Offset",detector,crystal),1.100);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <linear== env.GetValue(Form("Griffin.BGO.Back.%d.%d.Resolution.Linear",detector,crystal),0.00183744);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <quadratic== env.GetValue(Form("Griffin.BGO.Back.%d.%d.Resolution.Quadratic",detector,crystal),0.0000007);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <cubic== env.GetValue(Form("Griffin.BGO.Back.%d.%d.Resolution.Cubic",detector,crystal),0.);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <//=LaBr3> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <offset== env.GetValue(Form("LaBr3.%d.Resolution.Offset",detector),1.7006116);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <linear== env.GetValue(Form("LaBr3.%d.Resolution.Linear",detector),0.5009382);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <quadratic== env.GetValue(Form("LaBr3.%d.Resolution.Quadratic",detector),0.000065451219);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <cubic== env.GetValue(Form("LaBr3.%d.Resolution.Cubic",detector),0.);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <//=Sceptar> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <offset== env.GetValue(Form("Sceptar.%d.Resolution.Offset",detector),0.0);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <linear== env.GetValue(Form("Sceptar.%d.Resolution.Linear",detector),0.0);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <quadratic== env.GetValue(Form("Sceptar.%d.Resolution.Quadratic",detector),0.0);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <cubic== env.GetValue(Form("Sceptar.%d.Resolution.Cubic",detector),0.0);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <//=EightPi> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <offset== env.GetValue(Form("EightPi.%d.Resolution.Offset",detector),1.100);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <linear== env.GetValue(Form("EightPi.%d.Resolution.Linear",detector),0.00183744);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <quadratic== env.GetValue(Form("EightPi.%d.Resolution.Quadratic",detector),0.0000007);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <cubic== env.GetValue(Form("EightPi.%d.Resolution.Cubic",detector),0.);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <offset== env.GetValue(Form("EightPi.BGO.%d.Resolution.Offset",detector),1.100);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <linear== env.GetValue(Form("EightPi.BGO.%d.Resolution.Linear",detector),0.00183744);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <quadratic== env.GetValue(Form("EightPi.BGO.%d.Resolution.Quadratic",detector),0.0000007);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <cubic== env.GetValue(Form("EightPi.BGO.%d.Resolution.Cubic",detector),0.);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <offset== env.GetValue(Form("EightPi.BGO.%d.Resolution.Offset",detector),1.100);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <linear== env.GetValue(Form("EightPi.BGO.%d.Resolution.Linear",detector),0.00183744);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <quadratic== env.GetValue(Form("EightPi.BGO.%d.Resolution.Quadratic",detector),0.0000007);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <cubic== env.GetValue(Form("EightPi.BGO.%d.Resolution.Cubic",detector),0.);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <offset== env.GetValue(Form("EightPi.BGO.%d.Resolution.Offset",detector),1.100);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <linear== env.GetValue(Form("EightPi.BGO.%d.Resolution.Linear",detector),0.00183744);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <quadratic== env.GetValue(Form("EightPi.BGO.%d.Resolution.Quadratic",detector),0.0000007);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <cubic== env.GetValue(Form("EightPi.BGO.%d.Resolution.Cubic",detector),0.);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <//=DESCANT> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <offset== env.GetValue(Form("Descant.Blue.%d.Resolution.Offset",detector),0.0);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <linear== env.GetValue(Form("Descant.Blue.%d.Resolution.Linear",detector),0.0);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <quadratic== env.GetValue(Form("Descant.Blue.%d.Resolution.Quadratic",detector),0.009);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <cubic== env.GetValue(Form("Descant.Blue.%d.Resolution.Cubic",detector),0.0);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <offset== env.GetValue(Form("Descant.Green.%d.Resolution.Offset",detector),0.0);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <linear== env.GetValue(Form("Descant.Green.%d.Resolution.Linear",detector),0.0);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <quadratic== env.GetValue(Form("Descant.Green.%d.Resolution.Quadratic",detector),0.009);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <cubic== env.GetValue(Form("Descant.Green.%d.Resolution.Cubic",detector),0.0);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <offset== env.GetValue(Form("Descant.Red.%d.Resolution.Offset",detector),0.0);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <linear== env.GetValue(Form("Descant.Red.%d.Resolution.Linear",detector),0.0);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <quadratic== env.GetValue(Form("Descant.Red.%d.Resolution.Quadratic",detector),0.009);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <cubic== env.GetValue(Form("Descant.Red.%d.Resolution.Cubic",detector),0.0);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <offset== env.GetValue(Form("Descant.White.%d.Resolution.Offset",detector),0.0);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <linear== env.GetValue(Form("Descant.White.%d.Resolution.Linear",detector),0.0);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <quadratic== env.GetValue(Form("Descant.White.%d.Resolution.Quadratic",detector),0.009);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <cubic== env.GetValue(Form("Descant.White.%d.Resolution.Cubic",detector),0.0);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <offset== env.GetValue(Form("Descant.Yellow.%d.Resolution.Offset",detector),0.0);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <linear== env.GetValue(Form("Descant.Yellow.%d.Resolution.Linear",detector),0.0);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <quadratic== env.GetValue(Form("Descant.Yellow.%d.Resolution.Quadratic",detector),0.009);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <cubic== env.GetValue(Form("Descant.Yellow.%d.Resolution.Cubic",detector),0.0);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <double=fanoFactor = env.GetValue("Testcan.Resolution.FanoFactor",20.);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <//=Paces> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <offset== env.GetValue(Form("Paces.%d.Resolution.Offset",detector),0.0);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <linear== env.GetValue(Form("Paces.%d.Resolution.Linear",detector),0.0);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <quadratic== env.GetValue(Form("Paces.%d.Resolution.Quadratic",detector),0.0);> for level 2; ignored
Warning in <TEnvRec::ChangeValue>: duplicate entry <cubic== env.GetValue(Form("Paces.%d.Resolution.Cubic",detector),0.0);> for level 2; ignored

**Comment by VinzenzBildstein** [comment] 2019-03-06 17:56
Those are all warnings from duplicate entries in your settings file. Can you post that file here? It shouldn't have any influence on the program, but who knows.

**Comment by VinzenzBildstein** [comment] 2022-11-08 14:42
No activity in over three years, so I closed this.

**Closed** 2022-11-08 14:42 UTC
